# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: article
  hint: true
  unique: true
  contents:
    - name: headline
      type: EssenceText
      default: :article_headline
      hint: true
    - name: picture
      type: EssencePicture
      hint: true
    - name: text
      type: EssenceRichtext
      default: :article_text
      hint: true
- name: section_intro
  hint: true
  contents:
    - name: title
      type: EssenceText
    - name: subtitle
      type: EssenceText
    - name: description
      type: EssenceRichtext
- name: section
  hint: true
  contents:
    - name: layout
      type: EssenceSelect
      settings:
        select_values: ["picture_left", "picture_right", "picture_text"]
    - name: title
      type: EssenceText
    - name: subtitle
      type: EssenceText
    - name: description
      type: EssenceRichtext
    - name: picture
      type: EssencePicture
      hint: true
- name: card_section
  hint: true
  contents:
    - name: title
      type: EssenceText
    - name: subtitle
      type: EssenceText
    - name: grid
      type: EssenceSelect
      settings:
        select_values: ["1-col", "2-col", "3-col", "4-col"]
    - name: background
      type: EssenceSelect
      settings:
        select_values: ["none", "dark_blue", "beige"]
  nestable_elements:
    - card
- name: card
  hint: true
  contents:
    - name: layout
      type: EssenceSelect
      settings:
        select_values: ["picture_top", "picture_bottom", "picture_text"]
    - name: background
      type: EssenceSelect
      settings:
        select_values: ["dark_blue", "light_blue", "coral", "none"]
    - name: title
      type: EssenceText
    - name: subtitle
      type: EssenceText
    - name: description
      type: EssenceRichtext
    - name: picture
      type: EssencePicture
      hint: true
